
version: "2"
services:
  app:
    build: .
    image: dont_touch_face_api
    restart: always
    networks:
      my-network:
        aliases:
         - web-app
    environment:
     - VIRTUAL_HOST= touching-your-face-is-bad-for-ya.kaardorost.com
     - VIRTUAL_PROTO= uwsgi
#     - DHPARAM_GENERATION= 'false'
#     - HSTS= 'off'
     - HTTPS_METHOD= noredirect
    volumes:
      - ./static/:/usr/share/touching-face/static/
    ports:
      - "8181:5000"

networks:
    my-network:
#networks:
#  default:
#   external:
#      name: nginx-proxy


