
version: "2"
services:
  app:
    build: .
    image: api
    restart: always
    networks:
      my-network:
        aliases:
         - web-app
    environment:
     - VIRTUAL_HOST= touching-your-face-is-bad-for-ya.kaardorost.com
     - VIRTUAL_PROTO= uwsgi
#     - DHPARAM_GENERATION= 'false'
#     - HSTS= 'off'
     - HTTPS_METHOD= noredirect
    volumes:
      - ./static/:/usr/share/touching-face/static/
    ports:
      - "7575:5000"



  nginx-fastai:
     image: nginx:1.13.7
     container_name: nginx-fastai
     depends_on:
       - app
     volumes:
       - ./nginx.conf:/etc/nginx/conf.d/default.conf

     networks:
       - my-network
     ports:
       - 80:80
       - 443:443
networks:
    my-network:
#networks:
#  default:
#   external:
#      name: nginx-proxy


