
version: "2"
services:
  app:
    build: .
    image: api
    restart: always
    networks:
      my-network:
        aliases:
         - web-app
    environment:
     - VIRTUAL_HOST= touching-your-face-is-bad-for-ya.kaardorost.com
     - VIRTUAL_PROTO= uwsgi
#     - DHPARAM_GENERATION= 'false'
#     - HSTS= 'off'
     - HTTPS_METHOD= noredirect
    volumes:
      - ./static/:/usr/share/touching-face/static/
    ports:
      - "8181:5000"


