
version: "2"
services:
  app:
    build: .
    image: api
    restart: always
    networks:
      my-network:
        aliases:
         - flask-app
    environment:
     - VIRTUAL_HOST= insightfactory.app
     - VIRTUAL_PROTO= uwsgi
#     - DHPARAM_GENERATION= 'false'
#     - HSTS= 'off'
     - HTTPS_METHOD= noredirect
    links:
      - db
    volumes:
       - ./static/:/usr/share/insightfactory/static/
#      - .:/app
#      - ./app/flask_session
#      - ./app/sessions
    depends_on:
        - db
    ports:
      - "6868:5000"



  nginx:
     image: nginx:1.13.7
     container_name: nginx
     depends_on:
       - app
     volumes:
       - ./nginx.conf:/etc/nginx/conf.d/default.conf
       - ./crt_insightfactory.crt:/usr/share/nginx/ssl/crt_insightfactory.crt
       - ./key_insightfactory.key:/usr/share/nginx/ssl/key_insightfactory.key
       - ./static:/usr/share/static/
     networks:
       - my-network
     ports:
       - 80:80
       - 443:443
networks:
    my-network:
#networks:
#  default:
#   external:
#      name: nginx-proxy


